version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: trainuser
      POSTGRES_PASSWORD: trainpassword
      POSTGRES_DB: traindb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trainuser -d traindb"]
      interval: 5s
      timeout: 5s
      retries: 5
    

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/.env:/app/.env
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: traintogether-frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata: